import { useEffect } from 'react'
import { Link } from 'react-router-dom'
import BookmarkBar from './components/BookmarkBar'
import './App.css'

function Disclaimer() {
  useEffect(() => {
    document.title = 'Disclaimer | YouTubeToTranscript.io'
    return () => { document.title = 'YouTubeToTranscript.io' }
  }, [])

  return (
    <div className="min-h-screen bg-[#f9fafb] text-[#1a1a2e] leading-[1.8] font-sans">
      <BookmarkBar />
      {/* Navigation */}
      <nav className="bg-white/80 backdrop-blur-md border-b border-gray-200 sticky top-0 z-50">
        <div className="container mx-auto px-4 py-2">
          <div className="flex items-center justify-between">
            <Link to="/" className="flex items-center space-x-3">
              <div className="w-8 h-8 bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg flex items-center justify-center">
                <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
              </div>
              <span className="text-xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                YouTubeToTranscript.io
              </span>
            </Link>
            <div className="hidden md:flex items-center space-x-6 text-sm text-gray-600">
              <Link to="/blog" className="hover:text-blue-600 transition-colors">Blog</Link>
              <Link to="/about" className="hover:text-blue-600 transition-colors">About</Link>
              <Link to="/contact" className="hover:text-blue-600 transition-colors">Contact</Link>
              <Link to="/privacy-policy" className="hover:text-blue-600 transition-colors">Privacy Policy</Link>
              <Link to="/terms" className="hover:text-blue-600 transition-colors">Terms</Link>
              <Link to="/disclaimer" className="hover:text-blue-600 transition-colors">Disclaimer</Link>
            </div>
          </div>
        </div>
      </nav>

      <div className="max-w-[800px] mx-auto my-[60px] px-6 pb-20 bg-white rounded-2xl border border-[#e2e8f0]">
        <div className="py-10 px-10 pb-5 border-b border-[#f1f5f9]">
          <h1 className="text-2xl font-bold text-[#0f172a] mb-2">Disclaimer</h1>
          <span className="inline-block bg-[#f1f5f9] text-[#64748b] text-[0.85rem] py-1 px-3 rounded-full mt-1.5">
            Last Updated: February 2026
          </span>
        </div>

        <div className="p-8 pt-8">
          <p className="text-[#475569] mb-3.5 text-[0.97rem]">
            The information and tools provided on <strong>YouTubeToTranscript.io</strong> are for general informational and productivity purposes only. By using this website, you acknowledge and agree to the following:
          </p>

          <h2 className="text-[1.2rem] font-bold text-[#0f172a] mt-8 mb-3">1. Transcript Accuracy</h2>
          <p className="text-[#475569] mb-3.5 text-[0.97rem]">
            The transcripts generated by this tool are based on the captions or audio available in the original YouTube video. We do not guarantee that transcripts are 100% accurate. Accuracy may vary depending on audio quality, speaker accents, background noise, and the language of the video. Users should review and verify transcripts before relying on them for professional, legal, or academic purposes.
          </p>

          <h2 className="text-[1.2rem] font-bold text-[#0f172a] mt-8 mb-3">2. Not Affiliated with YouTube or Google</h2>
          <p className="text-[#475569] mb-3.5 text-[0.97rem]">
            YouTubeToTranscript.io is an independent tool and is not affiliated with, endorsed by, or connected to YouTube, Google LLC, or Alphabet Inc. in any way. All YouTube trademarks and brand names are the property of their respective owners.
          </p>

          <h2 className="text-[1.2rem] font-bold text-[#0f172a] mt-8 mb-3">3. Copyright and Intellectual Property</h2>
          <p className="text-[#475569] mb-3.5 text-[0.97rem]">
            The transcripts generated through this tool are derived from YouTube video content. The copyright of that content belongs to the original video creators. Users are solely responsible for ensuring they have the right to access, use, and share the transcript content generated through this tool. This tool should not be used to infringe upon the intellectual property rights of content creators.
          </p>

          <h2 className="text-[1.2rem] font-bold text-[#0f172a] mt-8 mb-3">4. Third-Party Links and Advertisements</h2>
          <p className="text-[#475569] mb-3.5 text-[0.97rem]">
            This website may display third-party advertisements or contain links to external websites. We are not responsible for the content, accuracy, or privacy practices of any third-party websites or advertisers. The presence of an advertisement or link does not constitute an endorsement.
          </p>

          <h2 className="text-[1.2rem] font-bold text-[#0f172a] mt-8 mb-3">5. Availability of Service</h2>
          <p className="text-[#475569] mb-3.5 text-[0.97rem]">
            We strive to keep YouTubeToTranscript.io available at all times, but we do not guarantee uninterrupted access. The service may be temporarily unavailable due to maintenance, updates, or factors beyond our control.
          </p>

          <h2 className="text-[1.2rem] font-bold text-[#0f172a] mt-8 mb-3">6. Limitation of Liability</h2>
          <p className="text-[#475569] mb-3.5 text-[0.97rem]">
            To the maximum extent permitted by law, YouTubeToTranscript.io and its owners shall not be held liable for any direct, indirect, incidental, or consequential damages resulting from the use of or inability to use this tool or any transcripts generated through it.
          </p>

          <h2 className="text-[1.2rem] font-bold text-[#0f172a] mt-8 mb-3">7. Contact</h2>
          <p className="text-[#475569] mb-3.5 text-[0.97rem]">If you have questions or concerns about this Disclaimer, please contact us at:</p>
          <p className="text-[#475569] mb-3.5 text-[0.97rem]"><strong>Email:</strong> <a href="mailto:contact@youtubetotranscript.io" className="text-indigo-500 no-underline hover:underline">contact@youtubetotranscript.io</a></p>
          <p className="text-[#475569] mb-3.5 text-[0.97rem]"><strong>Website:</strong> <a href="https://youtubetotranscript.io" className="text-indigo-500 no-underline hover:underline">youtubetotranscript.io</a></p>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-white/80 backdrop-blur-md border-t border-gray-200 mt-16">
        <div className="container mx-auto px-4 py-6 flex flex-col md:flex-row items-center justify-between text-sm text-gray-500">
          <p>&copy; {new Date().getFullYear()} <Link to="/" className="hover:text-blue-600 transition-colors">YouTubeToTranscript.io</Link>. All rights reserved.</p>
          <div className="flex flex-wrap justify-center gap-x-4 gap-y-1 mt-3 md:mt-0">
            <Link to="/" className="hover:text-blue-600 transition-colors">Back to Home</Link>
            <Link to="/blog" className="hover:text-blue-600 transition-colors">Blog</Link>
            <Link to="/about" className="hover:text-blue-600 transition-colors">About</Link>
            <Link to="/contact" className="hover:text-blue-600 transition-colors">Contact</Link>
            <Link to="/privacy-policy" className="hover:text-blue-600 transition-colors">Privacy Policy</Link>
            <Link to="/terms" className="hover:text-blue-600 transition-colors">Terms &amp; Conditions</Link>
            <Link to="/disclaimer" className="hover:text-blue-600 transition-colors">Disclaimer</Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

export default Disclaimer
